import express from 'express';import http from 'http';import {Server} from 'socket.io';import crypto from 'crypto';import fs from 'fs';import path from 'path';import {fileURLToPath} from 'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url)),app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:true}}),PORT=process.env.PORT||3000,DATA=path.join(__dirname,'data.json');
app.use(express.static(path.join(__dirname,'public')));app.get('/health',(q,s)=>s.json({ok:true,rooms:rooms.size}));
let db=fs.existsSync(DATA)?JSON.parse(fs.readFileSync(DATA,'utf8')):{users:{}};function save(){fs.writeFileSync(DATA,JSON.stringify(db,null,2))}const rooms=new Map(),users=new Map();
const WEATHER=[['clear','매우 맑음',1.04,.00045],['cloudy','흐림',1,.0006],['rain','비',.96,.0010],['storm','폭우',.91,.0018],['snow','눈',.93,.0012]].map(([id,name,speed,fall])=>({id,name,speed,fall}));
const SKILLS=[['천마폭주','내 영혼의 고삐를 풀어라아아!!',1.55],['흑염질주','검은 불꽃이여, 결승선을 삼켜라!',1.48],['시공가속','시간아… 잠깐만 느려져라!',1.42],['천상질풍','하늘을 달리는 것은 나다!',1.5],['황금심장','심장이 뛰는 한, 나는 멈추지 않는다!',1.44],['폭풍쇄도','폭풍조차 나의 뒤를 따른다!',1.53],['무한질주','한계? 그런 단어는 삭제했다!',1.47],['마왕강림','무릎 꿇어라! 결승선은 내 것이다!',1.56]].map(x=>({name:x[0],line:x[1],mult:x[2]}));
const hash=(p,s=crypto.randomBytes(16).toString('hex'))=>({salt:s,hash:crypto.scryptSync(p,s,64).toString('hex')});const verify=(p,o)=>crypto.timingSafeEqual(Buffer.from(o.hash,'hex'),crypto.scryptSync(p,o.salt,64));const token=()=>crypto.randomBytes(24).toString('hex');const rid=()=>crypto.randomBytes(4).toString('hex');const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function daily(u){const d=new Date().toISOString().slice(0,10);if(u.lastDaily!==d){u.lastDaily=d;u.coins=2000;save()}}function auth(t){return t&&[...Object.values(db.users)].find(u=>u.token===t)}
function makeRoom(name,privateRoom,password){const r={id:rid(),name,private:privateRoom,password:password||null,state:'lobby',users:[],weather:WEATHER[Math.floor(Math.random()*5)],horses:Array.from({length:8},(_,i)=>({lane:i,name:['번개','폭설','흑기사','초신성','질풍','백야','마왕','천마'][i]+'호',progress:0,speed:.00135+Math.random()*.00038,condition:.84+Math.random()*.32,fallen:false,injured:false,skill:SKILLS[i]})),lap:0,finishOrder:[],bets:new Map(),fee:0,startedAt:0};rooms.set(r.id,r);return r}
function info(r){return{id:r.id,name:r.name,private:r.private,runners:r.users.filter(x=>x.role==='runner').length,spectators:r.users.filter(x=>x.role==='spectator').length,state:r.state,weather:r.weather.name}}
function lobby(){io.emit('rooms',[...rooms.values()].filter(r=>!r.private).map(info))}function send(r){r.users.forEach(u=>io.to(u.socket).emit('roomState',{id:r.id,name:r.name,private:r.private,state:r.state,weather:r.weather,lap:r.lap,horses:r.horses,finishOrder:r.finishOrder,users:r.users.map(x=>({id:x.socket,nickname:x.nickname,role:x.role,coins:x.account?db.users[x.account].coins:x.coins,skillReady:x.skillReady}))}))}
function currentUser(socket){return users.get(socket.id)}
const translations={};async function translate(msg,target){if(target==='ko')return msg;const endpoint=process.env.TRANSLATE_API_URL;if(!endpoint)return msg;try{const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({q:msg,source:'auto',target,format:'text'})});const j=await r.json();return j.translatedText||msg}catch{return msg}}
async function translatedMap(msg){const out={ko:msg};for(const l of ['en','ja','zh'])out[l]=await translate(msg,l);return out}

io.on('connection',s=>{
 s.on('register',({username,password,nickname},cb)=>{if(!/^[A-Za-z0-9_]{3,20}$/.test(username||''))return cb({ok:false,error:'아이디는 영문/숫자/_ 3~20자입니다.'});if(!password||password.length<4)return cb({ok:false,error:'비밀번호는 4자 이상입니다.'});if(db.users[username])return cb({ok:false,error:'이미 존재하는 아이디입니다.'});const h=hash(password);db.users[username]={username,nickname:nickname?.slice(0,20)||username,...h,coins:2000,lastDaily:new Date().toISOString().slice(0,10),token:token()};save();cb({ok:true,username,nickname:db.users[username].nickname,coins:2000,token:db.users[username].token})});
 s.on('login',({username,password},cb)=>{const u=db.users[username];if(!u||!verify(password,u))return cb({ok:false,error:'아이디 또는 비밀번호가 올바르지 않습니다.'});daily(u);u.token=token();save();cb({ok:true,username,nickname:u.nickname,coins:u.coins,token:u.token})});
 s.on('getRooms',lobby);
 s.on('createRoom',({name,privateRoom,password,nickname,role,token:t},cb)=>{if(!nickname)return cb({ok:false,error:'닉네임을 입력하세요.'});const account=auth(t);if(account)daily(account);const r=makeRoom((name||'천마 경마장').slice(0,40),!!privateRoom,password);const u={socket:s.id,account:account?.username||null,nickname:nickname.slice(0,20),role,roomId:r.id,coins:account?account.coins:2000,skillReady:true};r.users.push(u);users.set(s.id,u);s.join(r.id);cb({ok:true,roomId:r.id,role});send(r);lobby()});
 s.on('joinRoom',({roomId,password,nickname,role,token:t},cb)=>{const r=rooms.get(roomId);if(!r)return cb({ok:false,error:'방을 찾을 수 없습니다.'});if(r.private&&r.password!==password)return cb({ok:false,error:'비밀번호가 올바르지 않습니다.'});if(r.users.length>=28)return cb({ok:false,error:'방 정원 28명이 가득 찼습니다.'});if(role==='runner'&&r.users.filter(x=>x.role==='runner').length>=8)return cb({ok:false,error:'주자 8명이 이미 찼습니다.'});if(role==='spectator'&&r.users.filter(x=>x.role==='spectator').length>=20)return cb({ok:false,error:'관전자 20명이 이미 찼습니다.'});const account=auth(t);if(account)daily(account);const u={socket:s.id,account:account?.username||null,nickname:(nickname||account?.nickname||'손님').slice(0,20),role,roomId,coins:account?account.coins:2000,skillReady:true};r.users.push(u);users.set(s.id,u);s.join(r.id);cb({ok:true,roomId,role});send(r);lobby()});
 s.on('startRace',()=>{const u=currentUser(s),r=u&&rooms.get(u.roomId);if(!r||u.role!=='runner'||r.state!=='lobby')return;if(r.users.filter(x=>x.role==='runner').length!==8)return s.emit('toast','주자 8명이 모두 모여야 합니다.');for(const x of r.users.filter(x=>x.role==='runner')){const a=x.account?db.users[x.account]:x;if(a.coins<100)return s.emit('toast',`${x.nickname}님의 참가비가 부족합니다.`)}for(const x of r.users.filter(x=>x.role==='runner')){const a=x.account?db.users[x.account]:x;a.coins-=100}save();r.state='running';r.startedAt=Date.now();r.lap=1;r.finishOrder=[];r.bets=new Map();r.fee=0;r.weather=WEATHER[Math.floor(Math.random()*5)];r.horses.forEach((h,i)=>{h.progress=0;h.fallen=false;h.injured=false;h.condition=.82+Math.random()*.36;h.speed=.00135+Math.random()*.00038});send(r)});
 s.on('useSkill',()=>{const u=currentUser(s),r=u&&rooms.get(u.roomId);if(!r||u.role!=='runner'||r.state!=='running'||!u.skillReady)return;const idx=r.users.filter(x=>x.role==='runner').findIndex(x=>x.socket===s.id);const h=r.horses[idx];if(!h)return;u.skillReady=false;h.speed*=h.skill.mult;io.to(r.id).emit('skill',{nickname:u.nickname,horse:h.name,skill:h.skill});setTimeout(()=>h.speed/=h.skill.mult,1800);setTimeout(()=>{u.skillReady=true;send(r)},12000)});
 s.on('placeBet',({horseIndex,amount})=>{const u=currentUser(s),r=u&&rooms.get(u.roomId);amount=Math.floor(+amount);horseIndex=Math.floor(+horseIndex);if(!r||u.role!=='spectator'||r.state!=='running')return s.emit('toast','진행 중인 경기에만 배팅할 수 있습니다.');if(!Number.isFinite(amount)||amount<1||amount>500)return s.emit('toast','1~500코인까지 배팅할 수 있습니다.');if(r.bets.has(s.id))return s.emit('toast','한 경기에는 1회만 배팅할 수 있습니다.');const a=u.account?db.users[u.account]:u;if(a.coins<amount)return s.emit('toast','코인이 부족합니다.');a.coins-=amount;r.bets.set(s.id,{socket:s.id,horseIndex,amount});r.fee+=Math.floor(amount*.05);save();s.emit('toast','배팅 완료!')});
 s.on('chat',async msg=>{const u=currentUser(s),r=u&&rooms.get(u.roomId);if(!r)return;msg=String(msg||'').trim().slice(0,300);if(!msg)return;const translations=await translatedMap(msg);io.to(r.id).emit('chat',{nickname:u.nickname,role:u.role,msg,translations})});
 s.on('disconnect',()=>{const u=users.get(s.id);if(!u)return;const r=rooms.get(u.roomId);if(r){r.users=r.users.filter(x=>x.socket!==s.id);if(!r.users.length)rooms.delete(r.id);else send(r);lobby()}users.delete(s.id)})
});
setInterval(()=>{for(const r of rooms.values()){if(r.state!=='running')continue;let max=0;r.horses.forEach(h=>{if(h.fallen)return;h.progress+=h.speed*r.weather.speed*h.condition*(.91+Math.random()*.16);if(Math.random()<r.weather.fall/10){h.fallen=true;h.injured=Math.random()<.45;h.speed*=.18;io.to(r.id).emit('incident',{horse:h.name,injured:h.injured})}max=Math.max(max,h.progress)});r.lap=clamp(Math.floor(max*5)+1,1,5);r.horses.forEach((h,i)=>{if(h.progress>=1&&!r.finishOrder.includes(i))r.finishOrder.push(i)});if(r.finishOrder.length===8||Date.now()-r.startedAt>120000){for(let i=0;i<8;i++)if(!r.finishOrder.includes(i))r.finishOrder.push(i);r.state='finished';const runners=r.users.filter(x=>x.role==='runner');[400,250,150].forEach((p,pos)=>{const u=runners[r.finishOrder[pos]];if(u){const a=u.account?db.users[u.account]:u;a.coins+=p}});const winner=runners[r.finishOrder[0]];if(winner){const a=winner.account?db.users[winner.account]:winner;a.coins+=r.fee}const total=r.bets? [...r.bets.values()].reduce((a,b)=>a+b.amount,0):0;const winHorse=r.finishOrder[0];const winningBets=r.bets?[...r.bets.values()].filter(b=>b.horseIndex===winHorse):[];const distributable=total-r.fee;const winningTotal=winningBets.reduce((a,b)=>a+b.amount,0);for(const b of winningBets){const bu=users.get(b.socket);if(bu){const ba=bu.account?db.users[bu.account]:bu;ba.coins+=Math.floor(distributable*b.amount/Math.max(1,winningTotal))}}save();send(r);io.to(r.id).emit('raceFinished',{order:r.finishOrder,fee:r.fee,betPool:total})}else send(r)}},100);
setInterval(()=>{for(const r of rooms.values())if(r.state==='running'){r.horses.forEach(h=>h.condition=.82+Math.random()*.36);io.to(r.id).emit('conditionChanged');send(r)}},600000);
server.listen(PORT,()=>console.log('천마 경마장 서버: '+PORT));
